### ISSUE TITLE
Where is the data logged to?

### ISSUE THREAD

**Issue by kevinwu** [EmPeWe/magento-api-logger#9]
I can't see the "EmPeWe_ApiLogger.log" file anywhere? Where is it?

**Comment by EmPeWe** [comment]
You can find it in {{magento_dir}}/var/log/

If not...
1. Did you succeed with the installation?
2. Did you make a request against the Mangento SOAP API?
3. Please tell me your api-logger configuration from Magento backend or take a screenshot.
4. What's your Magento version?
